-- MySQL Script generated by MySQL Workbench
-- Sun Jan 12 20:01:23 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`companies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`companies` ;

CREATE TABLE IF NOT EXISTS `mydb`.`companies` (
  `id_company` INT NOT NULL,
  `removed` INT(2) NOT NULL DEFAULT 0,
  `creation_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_company`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`passwords`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`passwords` ;

CREATE TABLE IF NOT EXISTS `mydb`.`passwords` (
  `id_password` INT NOT NULL,
  `creation_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_password`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cat_account_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cat_account_status` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cat_account_status` (
  `id_account_status` INT NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `creation_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_account_status`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id_user` INT NOT NULL,
  `name` VARCHAR(300) NOT NULL,
  `last_name` VARCHAR(300) NOT NULL,
  `phone_number` VARCHAR(45) NULL,
  `key_account_number` INT NULL,
  `ife_or_passport` VARCHAR(300) NULL,
  `payroll_receipt` VARCHAR(45) NULL,
  `proof_of_address` INT NULL,
  `photo` VARCHAR(45) NULL,
  `digital_signed_contract` VARCHAR(45) NULL,
  `security_pin` VARCHAR(45) NULL,
  `id_password` INT NOT NULL,
  `id_removed` INT(2) NOT NULL DEFAULT 0,
  `creation_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `iid_account_status` INT NOT NULL,
  PRIMARY KEY (`id_user`),
  CONSTRAINT `fk_users_passwords1`
    FOREIGN KEY (`id_password`)
    REFERENCES `mydb`.`passwords` (`id_password`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_cat_account_status1`
    FOREIGN KEY (`iid_account_status`)
    REFERENCES `mydb`.`cat_account_status` (`id_account_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_users_passwords1_idx` ON `mydb`.`users` (`id_password` ASC);

CREATE INDEX `fk_users_cat_account_status1_idx` ON `mydb`.`users` (`iid_account_status` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`paysheet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`paysheet` ;

CREATE TABLE IF NOT EXISTS `mydb`.`paysheet` (
  `id_paysheet` INT NOT NULL,
  `payroll_receipt_statement` VARCHAR(45) NULL,
  `company_contract` VARCHAR(45) NULL,
  `net_monthly_salary` VARCHAR(45) NULL,
  `registration_date` VARCHAR(45) NULL,
  `id_company` INT NOT NULL,
  `id_user` INT NOT NULL,
  `id_removed` INT(2) NOT NULL DEFAULT 0,
  `creation_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_paysheet`),
  CONSTRAINT `fk_paysheet_companies`
    FOREIGN KEY (`id_company`)
    REFERENCES `mydb`.`companies` (`id_company`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paysheet_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_paysheet_companies_idx` ON `mydb`.`paysheet` (`id_company` ASC);

CREATE INDEX `fk_paysheet_users1_idx` ON `mydb`.`paysheet` (`id_user` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`credit_advances`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`credit_advances` ;

CREATE TABLE IF NOT EXISTS `mydb`.`credit_advances` (
  `id_credit_advance` INT NOT NULL,
  `withdrawal_date` DATETIME NULL,
  `payment_date` DATETIME NULL,
  `benefits` VARCHAR(45) NULL,
  `withdrawals_amount` DECIMAL NULL,
  `commission` DECIMAL NULL,
  `IVA` VARCHAR(45) NULL,
  `total` VARCHAR(45) NULL,
  `balance` VARCHAR(45) NULL,
  `days_advance` INT NULL,
  `status` VARCHAR(45) NULL,
  `reason` VARCHAR(45) NULL,
  `collectable_uncollectible` VARCHAR(45) NULL,
  `description_status` VARCHAR(45) NULL,
  `credit_advancescol` VARCHAR(45) NULL,
  `id_paysheet` INT NOT NULL,
  `id_removed` INT(2) NULL,
  `creation_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_credit_advance`),
  CONSTRAINT `fk_credit_advances_paysheet1`
    FOREIGN KEY (`id_paysheet`)
    REFERENCES `mydb`.`paysheet` (`id_paysheet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_credit_advances_paysheet1_idx` ON `mydb`.`credit_advances` (`id_paysheet` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`credit_payments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`credit_payments` ;

CREATE TABLE IF NOT EXISTS `mydb`.`credit_payments` (
  `id_credit_payment` INT NOT NULL,
  `removed` INT(2) NOT NULL DEFAULT 0,
  `creation_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `id_credit_advance` INT NOT NULL,
  PRIMARY KEY (`id_credit_payment`),
  CONSTRAINT `fk_credit_payments_credit_advances1`
    FOREIGN KEY (`id_credit_advance`)
    REFERENCES `mydb`.`credit_advances` (`id_credit_advance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_credit_payments_credit_advances1_idx` ON `mydb`.`credit_payments` (`id_credit_advance` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`cat_record_states`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cat_record_states` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cat_record_states` (
  `id_removed` INT NOT NULL,
  `description` VARCHAR(100) NULL,
  `creation_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`timestamps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`timestamps` ;

CREATE TABLE IF NOT EXISTS `mydb`.`timestamps` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
